### ISSUE TITLE
Miss candidate with citar-denote-find-citation

### ISSUE THREAD

**Issue by Jousimies** [pprevos/citar-denote#19] opened 2023-03-22 03:55 UTC
For example, this is a note content.
---
#+title:      test
#+date: [2023-03-22 Wed 11:43]
#+filetags:   :bib:
#+identifier: 20230322T114151

This is a test[cite:@taerweluc2013].

-----

If there is a dot at the end of citation, when I use `citar-denote-find-citation` to find denote files related to citation `taerweluc2013`, it do not exist in the completion minibuffer. 

If I delete the dot, then use `citar-denote-find-citation`, the candidate appeared.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/72933939/226797483-6434d2ca-3c18-4a67-a60f-2daa0e6a9e7e.png">
with dot at the end of citation.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/72933939/226797562-f51848b2-bcff-47c7-9cf5-20f81e0cc706.png">
without dot.

-------------
Above picture shows, one reference disappeared. Any char at the end of citation will cause this problem.

**Comment by pprevos** [comment] 2023-03-22 07:00
Hi, I have been able to replicate the error. The issue is with `citar-denote-extract-citations`. I'll work on it tonight, should be an easy fix (regex issue).

**Comment by pprevos** [comment] 2023-03-22 07:11
It was a problem in a regular expression. Can you evaluate this function and confirm that it resolves the issue?

```
    (defun citar-denote-extract-citations ()
  "Extract citations from all Denote files."
  ;; Extract lines with citations
  (let* ((xrefs (xref-matches-in-files
                 citar-denote-citekey-regex
                 (denote-directory-text-only-files)))
         (citations (mapcar #'substring-no-properties
                            (mapcar #'xref-match-item-summary xrefs))))
    ;; Clean results
    (delete-dups
     (mapcar
      (lambda (cite)
        (replace-regexp-in-string
         "@\\|\\].*\\|;" ""  ;; Fixed issue 19
         (substring
          cite (string-match citar-denote-citekey-regex cite))))
      citations))))
```

**Comment by Jousimies** [comment] 2023-03-22 07:24
It worked, fantastic. 

Thank you for your great job.

**Comment by pprevos** [comment] 2023-03-22 07:39
No worries. I have committed the update, which will soon land in MELPA. 756682b

**Closed** 2023-03-22 07:39 UTC

**Comment by Jousimies** [comment] 2023-03-22 08:07
A mistake in 
https://github.com/pprevos/citar-denote/blob/756682bcaeeb28bfcdfddbcfe91de8bc28147f73/citar-denote.el#L262

You should delete this line.

**Comment by pprevos** [comment] 2023-03-22 08:44
Oops, that was silly. Fixed it.
